spring:
  profiles:
    active: dev

---

spring:
  profiles: dev
hazelcast:
  client:
    config: /Users/nklkarthi/github-projects/nklkarthi/pbcache-load-data/config/hazelcast-client-dev.xml

---

spring:
  profiles: sit

hazelcast:
  client:
    config: /Users/nklkarthi/github-projects/nklkarthi/pbcache-load-data/config/hazelcast-client-sit.xml

---
spring:
  profiles: uat
hazelcast:
  client:
    config: /Users/nklkarthi/github-projects/nklkarthi/pbcache-load-data/config/hazelcast-client-uat.xml

---
spring:
  profiles: prod
hazelcast:
  client:
    config: /Users/nklkarthi/github-projects/nklkarthi/pbcache-load-data/config/hazelcast-client-prod.xml